### ISSUE TITLE
Welly refactor plan

### ISSUE THREAD

**Issue by patrick-reinhard** [patrick-reinhard/welly#5]
**Part 1** -- To ensure separation of concerns, move out methods of the class to dedicated modules:
- [x] QC logic (Well, Curve): Move out QC test orchestrator logic from class methods to quality.py module 
(#3)
- [x] Plotting logic (Project, Well, Curve): Create plot.py module with functions that operate on the class objects 
(#3)
- [x] Reader/writer logic (Project, Well, Curve): Move out reader/writer logic from class methods to las.py module with functions that return raw pandas objects that are 1:1 reflections of files (e.g. .las) 
(#4)

**Part 2** -- Replace curve object with pandas by extension, needs to support n-column to support multivariate channels:
- [x] Use one of the options from pandas/xarray extension documentation ordered list of preference (composition, custom accessor, extension array, subclassing)
(#6 )
- [x] Replace all interface points that are replicating pandas/xarray functionality by pandas/xarray native functionality 
(QC, smoothing, index, interpolation, find nearest, pandas plotting)
- [x] Where necessary, adapt interfaces to curve in plotting and/or QC modules and from wells/projects. Otherwise, Well and Project should remain unchanged

**Part 3** -- Update tutorials, demos:
- [ ] Reliant on the above, do once done; can partially start during part 2
- [ ] User testing, iteration on refactor parts 2

![welly](https://user-images.githubusercontent.com/59961184/139583377-5ae9cf5e-619a-4d69-b560-65e8cb9d8a2e.jpg)
